In [1]:
import numpy as np

# To convert a list of numeric values into a one-dimensional NumPy array


In [2]:
# Your list of numeric values
list = [1, 2, 3, 4, 5]

# Convert the list to a NumPy array
Array = np.array(list)

# Print the resulting NumPy array
print(Array)

[1 2 3 4 5]


# To create a 3x3 matrix with values ranging from 2 to 10

In [3]:
# Create a 1-dim array of values ranging from 2 to 10
values = np.arange(2, 11)

# Reshape the 1-dim array into a 3x3 matrix
matrix = values.reshape(3,3)

# Print the resulting matrix
print(matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


# To append values at the end of an array

In [4]:
# 1 dim append
x = [10, 20, 30]
print(x)

#To append values at the end of an array
x = np.append(x,np.random.randint(0, 10),)
print("After append values to the end of the array:")
print(x)

[10, 20, 30]
After append values to the end of the array:
[10 20 30  0]


In [5]:
#2 dim append
original_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(original_array)
print("\n")

ran=np.random.randint(11, 21,(3, 3))
print(ran)
print("\n")

y = np.append(original_array,ran,axis=0)
# Print the resulting 
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[17 12 19]
 [18 17 12]
 [14 14 18]]


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [17 12 19]
 [18 17 12]
 [14 14 18]]


# To create another shape from an array without changing its data(3x2 to 2x3) 

In [6]:
import numpy as np

# Create a 3x2 array
original_array =np.random.randint(0, 21,(3, 2))

# Reshape the array to 2x3
reshaped_array = original_array.reshape(2, 3)

# Print the original and reshaped arrays
print("Original array:")
print(original_array)
print("\nReshaped array:")
print(reshaped_array)

Original array:
[[ 5 10]
 [ 7 19]
 [ 6 13]]

Reshaped array:
[[ 5 10  7]
 [19  6 13]]
