To convert a list of numeric values into a one-dimensional NumPy array


In [1]:
import numpy as np

# Your list of numeric values
list = [1, 2, 3, 4, 5]

# Convert the list to a NumPy array
Array = np.array(list)

# Print the resulting NumPy array
print(Array)


[1 2 3 4 5]


To create a 33 matrix with values ranging from 2 to 10

In [2]:
import numpy as np

# Create a 1-dim array of values ranging from 2 to 10
values = np.arange(2, 11)

# Reshape the 1-dim array into a 3x3 matrix
matrix = values.reshape(3,3)

# Print the resulting matrix
print(matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


To append values at the end of an array

In [3]:
import numpy as np
# 1 dim append
x = [10, 20, 30]
print(x)

#To append values at the end of an array
x = np.append(x,np.random.randint(0, 10),)
print("After append values to the end of the array:")
print(x)

#2 dim append
print("2 dim")
original_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(original_array)
ran=np.random.randint(11, 21,(3, 3))
print(ran)
y = np.append(original_array,ran,axis=0)
# Print the resulting 

print(y)

[10, 20, 30]
After append values to the end of the array:
[10 20 30  1]
2 dim
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[12 18 13]
 [13 19 20]
 [18 20 13]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [12 18 13]
 [13 19 20]
 [18 20 13]]


To create another shape from an array without changing its data(3*2 
to 2*3) 

In [4]:
import numpy as np

# Create a 3x2 array
original_array =np.random.randint(0, 21,(3, 2))

# Reshape the array to 2x3
reshaped_array = original_array.reshape(2, 3)

# Print the original and reshaped arrays
print("Original array:")
print(original_array)
print("\nReshaped array:")
print(reshaped_array)

Original array:
[[ 8 16]
 [15 18]
 [ 5  5]]

Reshaped array:
[[ 8 16 15]
 [18  5  5]]
